### ISSUE TITLE
Expose the --include option of deboostrap in the configuration

### ISSUE THREAD

**Issue by em-** [go-debos/debos#18]
When deboostrapping HTTPS-based repositories the `apt-transport-https` and `ca-certificates` should be installed right from the start, and that's usually handled with the `--include` option.

In my specific case their availability is probably better ensured through a custom debootstrap script (see #16), but I wonder if there's value in exposing more deboostrap options.

**Comment by sjoerdsimons** [comment]
`debootstrap (1.0.59) unstable; urgency=medium

  * Install ca-certificates as well as apt-transport-https for HTTPS
    installations.  This makes it possible to copy certificates that were
    built into the installer to /usr/local/share/ca-certificates/ and thus
    have them continue to be trusted after installation.
`

So in debian since wheezy and ubuntu since trusty :)

Fwiw I'm wary about given direct access to --include, debootstraps dependency resolver is.. lets say basic. So it's quite easy to break things if using include, the preferred way is to debootstrap and then use apt actions for everything else.

In the exceptional case (like the https transport) where you really need to install extra things during debootstrap, I think debos needs to handle that internally.. The only other example i can think of is the keyring package, but that's a bit of a chicken and egg issue that we can hopefully flush out as part of #21.
